image: "rust:latest"

before_script:
- apt-get update -yqq
- apt-get install -yqq --no-install-recommends build-essential

variables:
    CARGO_HOME: "$CI_PROJECT_DIR/.cargo/"
    TARGET_DIR: "$CI_PROJECT_DIR/target/"


stages:
  - test

"cargo test":
  stage: test
  cache:
    key: cargo-test
    paths:
      - "$CARGO_HOME"
      - "$TARGET_DIR"
  script:
  - rustc --version && cargo --version
  - cargo test --all --verbose

