language: rust
cache: cargo
rust:
  - stable
  - beta
addons:
  apt:
    packages:
      # for kcov build
      - binutils-dev
      - libcurl4-openssl-dev
      - zlib1g-dev
      - libdw-dev
      - libiberty-dev
      - libelf-dev
      - cmake
      - gcc
      - pkg-config
      - jq

jobs:
  include:
    - stage: "Coverage"
      name: "cargo-kcov"
      script:
        - cargo kcov --version || cargo install cargo-kcov
        - |
            [[ -x $HOME/.cargo/bin/kcov ]] && echo "kcov bin found in cache" || cargo kcov --print-install-kcov-sh | sh
        # FIXME: When rust-lang/rust#52478 is fixed, we can get rid of the
        # extra build step and allow cargo kcov to build it, using the "-C
        # link-dead-code" flag, to get more accurate coverage numbers.
        - cargo test --verbose --no-run
        - cargo kcov --verbose --no-clean-rebuild --coveralls
