language: rust
cache: cargo
rust:
  - stable
  - beta
addons:
  apt:
    packages:
      # for kcov build
      - binutils-dev
      - libcurl4-openssl-dev
      - zlib1g-dev
      - libdw-dev
      - libiberty-dev
      - libelf-dev
      - cmake
      - gcc
      - pkg-config
      - jq

jobs:
  include:
    - stage: "Coverage"
      name: "cargo-kcov"
      script:
        - cargo clean
        - echo $CARGO_HOME
        - cargo kcov --version || cargo install cargo-kcov
        - |
            if ([[ -x $HOME/.cargo/bin/kcov ]] && (kcov --version | grep -q 'kcov 36'))
              then echo "kcov bin found in cache" && export KCOV_FOUND=1
            fi
        - if [[ -z $KCOV_FOUND ]]; then (cargo kcov --print-install-kcov-sh | bash); fi
        # sqlite3-sys outputs a bindgen file that kcov picks up when we link dead code for whatever reason
        - cargo kcov --verbose --coveralls -- --exclude-pattern="bindgen.rs,$HOME/.cargo"
        # clean again to get rid of artifacts with different link flags
        - cargo clean
