[package]
name = "taskerizer-prototype"
version = "0.1.0"
authors = ["Harry Stern <hcs@meow.sh>"]

[dependencies]
structopt = "0.2"
failure = "0.1"
rusqlite = { version = "0.14", features = ["chrono"] }
chrono = "0.4"


[dev-dependencies]
proptest = "0.8"
tempfile = "3"
